name: ClassicPress Directory Coding Standard checks.

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: CPCS Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install PHPCS and WPCS (ClassicPress Standard)
        run: |
          composer global require squizlabs/php_codesniffer:"*" wp-coding-standards/wpcs:"2.3.0"
          ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Download Coding Standard Ruleset
        run: |
          wget -O phpcs.xml https://raw.githubusercontent.com/ClassicPress/ClassicPress-Coding-Standards/main/phpcs.xml
          sed -i '/^\t<!-- start config -->/a\
            <file>.</file>
          ' phpcs.xml
          sed -i 's/MY_DOMAIN/inheritance/' phpcs.xml
          mv phpcs.xml phpcs.xml.dist

      - name: Run PHPCS with CPCS Ruleset
        run: |
          ~/.composer/vendor/bin/phpcs --standard=phpcs.xml.dist --report=json --report-file=phpcs.json .

      - name: Generate Markdown Summary
        if: always()
        run: |
          npm install -g github:10up/phpcs-json-to-md
          if [ -f phpcs.json ]; then
            phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
            cat ./phpcs.md >> $GITHUB_STEP_SUMMARY
          else
            echo "PHPCS did not generate a report." >> $GITHUB_STEP_SUMMARY
          fi
name: ClassicPress Directory Coding Standard checks.

on:
  push:
    branches:
      - develop

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  phpcs:
    name: CPCS Checks
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP and Composer
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
          tools: composer

      - name: Install PHPCS and WPCS (ClassicPress Standard)
        run: |
          composer global require squizlabs/php_codesniffer:"*" wp-coding-standards/wpcs:"2.3.0"
          ~/.composer/vendor/bin/phpcs --config-set installed_paths ~/.composer/vendor/wp-coding-standards/wpcs

      - name: Download Coding Standard Ruleset
        run: |
          wget -O phpcs.xml https://raw.githubusercontent.com/ClassicPress/ClassicPress-Coding-Standards/main/phpcs.xml
          sed -i '/^\t<!-- start config -->/a\
            <file>.</file>
          ' phpcs.xml
          sed -i 's/MY_DOMAIN/inheritance/' phpcs.xml
          mv phpcs.xml phpcs.xml.dist

      - name: Run PHPCS with CPCS Ruleset
        run: |
          ~/.composer/vendor/bin/phpcs --standard=phpcs.xml.dist --report=json --report-file=phpcs.json .

      - name: Generate Markdown Summary
        if: always()
        run: |
          npm install -g github:10up/phpcs-json-to-md
          if [ -f phpcs.json ]; then
            phpcs-json-to-md --path ./phpcs.json --output ./phpcs.md
            cat ./phpcs.md >> $GITHUB_STEP_SUMMARY
          else
            echo "PHPCS did not generate a report." >> $GITHUB_STEP_SUMMARY
          fi
